### PR TITLE
chore(lint): use eslint-config-helix

### PR DESCRIPTION
**Pull request by tripodsan**
@koraa maybe you can adjust it to your liking ;-)

### CODE REVIEW

**Comment by koraa** [comment]
Hi. Thanks for your PR!

Honestly, I don't see this being much of an improvement. Could you please explain why each of those changes does represent an improvement?

**Comment by koraa** [comment]
You have also removed quite a few rules which are completely standard in all helix repos (e.g. just allowing one statement per line). Could you please explain specifically why those where removed?

**Comment by tripodsan** [comment]
the _stricter_ rules come from the update of the underlying aribnb eslint config.
I think that:
- having a consistent notation for arrow functions makes it easier when developing and reviewing.
- having only 1 statement per line gives more clarity and produces clearer diffs and commenting abilities


As for the other rules, I added them to the `.eslintrc.js`. we might add them to our eslint config.

**Comment by koraa** [comment]
@tripodsan ++1. I think it would be great to add them to the central lint config!

**Pull request merged**
